eveauth/apps/eve_auth/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from bootstrap.urls import bootstrap_list, bootstrap_create, bootstrap_update, bootstrap_delete
from forms import APIKeyForm
from models import APIKey
from views import *

from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

from account.views import SignupView
urlpatterns = patterns('',
        bootstrap_list(r'^$', 'apikey_list', model=APIKey, view=APIKeyListView.as_view()),
        bootstrap_create(r'^add/$', 'apikey_add', view=APIKeyCreateView.as_view(), form=APIKeyForm),
        bootstrap_update(r'^(?P<pk>\d+)/update/$', 'apikey_update', view=APIKeyUpdateView.as_view(), form=APIKeyForm),
        bootstrap_delete(r'^(?P<pk>\d+)/delete/$', 'apikey_delete', view=APIKeyDeleteView.as_view(), model=APIKey),
)

urlpatterns += patterns('',
        url(r'^characters/$', CharacterListView.as_view(), name="character_list"),
        url(r'^characters/update/$', CharacterUpdateView.as_view(), name="character_update"),
        url(r"^characters/default/$", DefaultCharacterView.as_view(), name="default_character"),
)

eveauth/apps/forum/urls.py
from django.conf.urls import *
from django.conf import settings

from forum import app_settings

urlpatterns = patterns('forum.views',
    url(r'^$',                                           'forum_index',              name='forum_index'),
    url(r'^search/$',                                    'search',                   name='forum_search'),
    url(r'^search_results/(?P<search_id>\d+)/$',         'search_results',           name='forum_search_results'),
    url(r'^new_posts/$',                                 'new_posts',                name='forum_new_posts'),
    url(r'^stalk_users/$',                               'stalk_users',              name='forum_stalk_users'),
    url(r'^add_section/$',                               'add_section',              name='forum_add_section'),
    url(r'^section/(?P<section_id>\d+)/$',               'section_detail',           name='forum_section_detail'),
    url(r'^section/(?P<section_id>\d+)/edit/$',          'edit_section',             name='forum_edit_section'),
    url(r'^section/(?P<section_id>\d+)/delete/$',        'delete_section',           name='forum_delete_section'),
    url(r'^section/(?P<section_id>\d+)/add_forum/$',     'add_forum',                name='forum_add_forum'),
    url(r'^forum/(?P<forum_id>\d+)/$',                   'forum_detail',             name='forum_forum_detail'),
    url(r'^forum/(?P<forum_id>\d+)/edit/$',              'edit_forum',               name='forum_edit_forum'),
    url(r'^forum/(?P<forum_id>\d+)/delete/$',            'delete_forum',             name='forum_delete_forum'),
    url(r'^forum/(?P<forum_id>\d+)/add_topic/$',         'add_topic',                name='forum_add_topic'),
    url(r'^topic/(?P<topic_id>\d+)/$',                   'topic_detail',             {'meta': False}, name='forum_topic_detail'),
    url(r'^topic/(?P<topic_id>\d+)/edit/$',              'edit_topic',               name='forum_edit_topic'),
    url(r'^topic/(?P<topic_id>\d+)/reply/$',             'add_reply',                {'meta': False}, name='forum_add_reply'),
    url(r'^topic/(?P<topic_id>\d+)/last_post/$',         'redirect_to_last_post',    name='forum_redirect_to_last_post'),
    url(r'^topic/(?P<topic_id>\d+)/unread_post/$',       'redirect_to_unread_post',  name='forum_redirect_to_unread_post'),
    url(r'^topic/(?P<topic_id>\d+)/delete/$',            'delete_topic',             name='forum_delete_topic'),
    url(r'^topic/(?P<topic_id>\d+)/meta/$',              'topic_detail',             {'meta': True}, name='forum_topic_meta_detail'),
    url(r'^topic/(?P<topic_id>\d+)/meta/reply/$',        'add_reply',                {'meta': True}, name='forum_add_meta_reply'),
    url(r'^topic/(?P<topic_id>\d+)/summary/$',           'topic_post_summary',       name='forum_topic_post_summary'),
    url(r'^post/(?P<post_id>\d+)/$',                     'redirect_to_post',         name='forum_redirect_to_post'),
    url(r'^post/(?P<post_id>\d+)/edit/$',                'edit_post',                name='forum_edit_post'),
    url(r'^post/(?P<post_id>\d+)/quote/$',               'quote_post',               name='forum_quote_post'),
    url(r'^post/(?P<post_id>\d+)/delete/$',              'delete_post',              name='forum_delete_post'),
    url(r'^user/(?P<user_id>\d+)/$',                     'user_profile',             name='forum_user_profile'),
    url(r'^user/(?P<user_id>\d+)/topics/$',              'user_topics',              name='forum_user_topics'),
    url(r'^user/(?P<user_id>\d+)/edit_profile/$',        'edit_user_forum_profile',  name='forum_edit_user_forum_profile'),
    url(r'^user/edit_forum_settings/$',                  'edit_user_forum_settings', name='forum_edit_user_forum_settings'),
)

if app_settings.STANDALONE:
    from django.contrib import admin
    admin.autodiscover()
    urlpatterns += patterns('',
        (r'^admin/', include(admin.site.urls)),
    )

eveauth/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

from account.views import SignupView

urlpatterns = patterns("",
    url(r"^$", direct_to_template, {"template": "homepage.html"}, name="home"),
    url(r"^auth/", include('eve_auth.urls')),
    url(r"^admin/", include(admin.site.urls)),
    url(r'^reddit/', include("vreddit.urls")), 
    url(r"^account/signup/$", SignupView.as_view(), name="account_signup"),
    url(r"^account/", include("account.urls")),
    url(r"^oauth/", include('oauth_provider.urls')),
    url(r"^forum/", include('forum.urls')),
    url(r"^corps/", include('corpmgr.urls')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eveauth/apps/forum/models.py
"""
Models for a discussion forum.
"""
import datetime
import logging
from itertools import izip

from django.contrib.auth.models import User
from django.db import connection, models, transaction
from django.utils.encoding import smart_unicode
from django.utils.text import truncate_words
from django.utils import timezone

from forum import app_settings
from forum.formatters import post_formatter
from forum.utils import models as model_utils
from pytz import common_timezones

from corpmgr.models import CorporationProfile, AllianceProfile

from eve_auth.models import Character, DefaultCharacter

from django.conf import settings

if app_settings.USE_REDIS:
    from forum import redis_connection as redis

__all__ = ['ForumProfile', 'Section', 'Forum', 'Topic',  'Post', 'Search']

qn = connection.ops.quote_name

class ForumProfileManager(models.Manager):
    def get_for_user(self, user):
        """
        Returns the Forum Profile for the given User, creating it first
        if necessary and caching it in the User the first time it is
        looked up.
        """
        if not hasattr(user, '_forum_profile_cache'):
            profile, created = self.get_or_create(user=user)
            user._forum_profile_cache = profile
        return user._forum_profile_cache

    def update_post_counts_in_bulk(self, user_ids):
        """
        Updates ``post_count`` for Users with the given ids.
        """
        opts = self.model._meta
        post_opts = Post._meta
        query = """
        UPDATE %(forum_profile)s
        SET %(post_count)s = (
            SELECT COUNT(*)
            FROM %(post)s
            WHERE %(post)s.%(post_user_fk)s=%(forum_profile)s.%(user_fk)s
        )
        WHERE %(user_fk)s IN (%(user_pks)s)""" % {
            'forum_profile': qn(opts.db_table),
            'post_count': qn(opts.get_field('post_count').column),
            'post': qn(post_opts.db_table),
            'post_user_fk': qn(post_opts.get_field('user').column),
            'user_fk': qn(opts.get_field('user').column),
            'user_pks': ','.join(['%s'] * len(user_ids)),
        }
        cursor = connection.cursor()
        cursor.execute(query, user_ids)

TIMEZONE_CHOICES = tuple([(tz, tz) for tz in common_timezones])

TOPICS_PER_PAGE_CHOICES = (
    (10, '10'),
    (20, '20'),
    (30, '30'),
    (40, '40'),
)

POSTS_PER_PAGE_CHOICES = (
    (10, '10'),
    (20, '20'),
    (30, '30'),
    (40, '40'),
)

class ForumProfile(models.Model):
    """
    Forum-specific information and configuration details for a User.
    """
    USER_GROUP      = 'U'
    MODERATOR_GROUP = 'M'
    ADMIN_GROUP     = 'A'

    GROUP_CHOICES = (
        (USER_GROUP, 'Users'),
        (MODERATOR_GROUP, 'Moderators'),
        (ADMIN_GROUP, 'Admins'),
    )

    user     = models.ForeignKey(User, unique=True, related_name='forum_profile')
    group    = models.CharField(max_length=1, choices=GROUP_CHOICES, default=USER_GROUP)
    title    = models.CharField(max_length=100, blank=True)
    location = models.CharField(max_length=100, blank=True)
    avatar   = models.URLField(max_length=200, verify_exists=False, blank=True)
    website  = models.URLField(max_length=200, verify_exists=False, blank=True)

    # Board settings
    timezone        = models.CharField(max_length=25, choices=TIMEZONE_CHOICES, blank=True)
    topics_per_page = models.PositiveIntegerField(choices=TOPICS_PER_PAGE_CHOICES, null=True, blank=True)
    posts_per_page  = models.PositiveIntegerField(choices=POSTS_PER_PAGE_CHOICES, null=True, blank=True)
    auto_fast_reply = models.BooleanField(default=False)

    # Denormalised data
    post_count = models.PositiveIntegerField(default=0)

    objects = ForumProfileManager()

    def __unicode__(self):
        return 'Forum profile for %s' % self.user

    class Meta:
        ordering = ('user',)

    @models.permalink
    def get_absolute_url(self):
        return ('forum_user_profile', (smart_unicode(self.user_id),))

    def is_moderator(self):
        """
        Returns ``True`` if the User represented by this ForumProfile has
        moderation privileges, ``False`` otherwise.
        """
        return self.group in (self.MODERATOR_GROUP, self.ADMIN_GROUP)

    def is_admin(self):
        """
        Returns ``True`` if the User represented by this ForumProfile has
        administrative privileges, ``False`` otherwise.
        """
        return self.group == self.ADMIN_GROUP

    def is_in_director_group(self, profile_object):
        pass

    def update_post_count(self):
        """
        Updates this ForumProfile's ``post_count`` with the number of
        Posts currently associated with its User.
        """
        self.post_count = self.user.posts.count()
        model_utils.update(self, 'post_count')
    update_post_count.alters_data = True

class SectionManager(models.Manager):
    def get_forums_by_section(self):
        """
        Yields ordered two-tuples of (section, forums).
        """
        section_forums = {}
        for forum in Forum.objects.all():
            section_forums.setdefault(forum.section_id, []).append(forum)
        for section in super(SectionManager, self).get_query_set():
            yield section, section_forums.get(section.pk, [])

    def increment_orders(self, start_at):
        """
        Increments ``order`` for all Sections which have an ``order``
        greater than or equal to ``start_at``.
        """
        self._change_orders(start_at, '+1')

    def decrement_orders(self, start_at):
        """
        Increments ``order`` for all Sections which have an ``order``
        greater than or equal to ``start_at``.
        """
        self._change_orders(start_at, '-1')

    def _change_orders(self, start_at, change):
        opts = self.model._meta
        cursor = connection.cursor()
        cursor.execute("""
            UPDATE %(section_table)s
            SET %(order)s=%(order)s%(change)s
            WHERE %(order)s>=%%s""" % {
                'section_table': qn(opts.db_table),
                'order': qn(opts.get_field('order').column),
                'change': change,
            }, [start_at])

    def get_authorized_by_section(self, user):
        """
        Yields ordered two-tuples of (section, forums) that this user can access.
        """
        section_forums = {}
        for forum in Forum.objects.all():
            section_forums.setdefault(forum.section_id, []).append(forum)
        for section in super(SectionManager, self).get_query_set():
            mgmt = section.is_managed()
            if mgmt:
                if section.alliance_owner is not None:
                    if section.alliance_owner.alliance.has_member(user):
                        yield section, section_forums.get(section.pk, [])
                elif section.corporate_owner is not None:
                    if section.corporate_owner.corporation.has_member(user):
                        yield section, section_forums.get(section.pk, [])
            else:
                yield section, section_forums.get(section.pk, [])

class Section(models.Model):
    """
    Provides categorisation for forums.
    """
    name  = models.CharField(max_length=100, unique=True)
    order = models.PositiveIntegerField()

    if "corpmgr" in settings.INSTALLED_APPS:
        corporate_owner = models.ForeignKey(CorporationProfile, related_name='corp_forum_sections', null=True, blank=True)
        alliance_owner = models.ForeignKey(AllianceProfile, related_name='alliance_forum_sections', null=True, blank=True)

    objects = SectionManager()


    def __unicode__(self):
        return self.name

    def delete(self):
        """
        This method is overridden to maintain consecutive ordering and
        to update the Post counts of any Users who had Posts in this
        Section.
        """
        affected_user_ids = [user['id'] for user in \
            User.objects.filter(posts__topic__forum__section=self) \
                         .distinct() \
                          .values('id')]
        super(Section, self).delete()
        Section.objects.decrement_orders(self.order)
        if len(affected_user_ids):
            ForumProfile.objects.update_post_counts_in_bulk(affected_user_ids)
        transaction.commit_unless_managed()

    class Meta:
        ordering = ('order',)

    @models.permalink
    def get_absolute_url(self):
        return ('forum_section_detail', (smart_unicode(self.pk),))

    def is_managed(self):
        if "corpmgr" in settings.INSTALLED_APPS:
            if self.alliance_owner is not None:
                return self.alliance_owner
            elif self.corporate_owner is not None:
                return self.corporate_owner

            return False
        else:
            return False

    def is_corp_authed(self, user):
        if "corpmgr" in settings.INSTALLED_APPS:
            if self.alliance_owner is not None:
                return self.alliance_owner.alliance.has_member(user)
            elif self.corporate_owner is not None:
                return self.corporate_owner.corporation.has_member(user)

            return False

        else:
            return True

class ForumManager(models.Manager):
    def increment_orders(self, section_id, start_at):
        """
        Increments ``order`` for all Forums in the given Section which
        have an ``order`` greater than or equal to ``start_at``.
        """
        self._change_orders(section_id, start_at, '+1')

    def decrement_orders(self, section_id, start_at):
        """
        Decrements ``order`` for all Forums in the given Section which
        have an ``order`` greater than or equal to ``start_at``.
        """
        self._change_orders(section_id, start_at, '-1')

    def _change_orders(self, section_id, start_at, change):
        opts = self.model._meta
        cursor = connection.cursor()
        cursor.execute("""
            UPDATE %(forum_table)s

eveauth/apps/forum/utils/models.py
from django.db import connection, transaction

def update(model_instance, *args):
    """
    Updates only specified fields of the given model instance.
    """
    opts = model_instance._meta
    fields = [opts.get_field(f) for f in args]
    db_values = [f.get_db_prep_save(f.pre_save(model_instance, False),connection) for f in fields]
    if db_values:
        connection.cursor().execute("UPDATE %s SET %s WHERE %s=%%s" % \
            (connection.ops.quote_name(opts.db_table),
             ','.join(['%s=%%s' % connection.ops.quote_name(f.column) for f in fields]),
             connection.ops.quote_name(opts.pk.column)),
             db_values + opts.pk.get_db_prep_lookup('exact', model_instance.pk, connection))
        transaction.commit_unless_managed()

eveauth/apps/forum/templates/forum/add_section.html
{% extends "forum/base.html" %}
{% block main_content %}
<form name="addSectionForm" id="addSectionForm" action="." method="POST">
{% csrf_token %}
  <fieldset class="module aligned">
    <h2>Section</h2>
    <div class="form-row">
      {% if form.name.errors %}{{ form.name.errors.as_ul }}{% endif %}
      {{ form.name.label_tag }}
      <div class="form-field">
        {{ form.name }}
      </div>
    </div>
    <div class="form-row">
      {% if form.section.errors %}{{ form.section.errors.as_ul }}{% endif %}
      <label for="id_section">Insert before</label>
      <div class="form-field">
        {{ form.section }}
        <p class="help">Leave this field blank to insert the new Section at the end.</p>
      </div>
    </div>
  </fieldset>
  <div class="buttons">
    <input type="submit" name="submit" value="Add Section">
    or
    <a href="{% url forum_index %}">Cancel</a>
  </div>
</form>
{% endblock %}

eveauth/apps/forum/templates/forum/base.html
{% extends "base_forum.html" %}
{% block extra_head %} {{ block.super }}<script type="text/javascript" src="{{ STATIC_URL }}forum/js/jquery-1.2.1.pack.js"></script>{% endblock %}

{% block breadcrumbs %}
<li><a href="{% url forum_index %}">Forums</a></li>
{% if section %}{% ifnotequal section.name title %} <span class="divider">/</span><li> <a href="{{ section.get_absolute_url }}">{{ section.name }}</a></li>{% endifnotequal %}{% endif %}
{% if forum %}{% ifnotequal forum.name title %} <span class="divider">/</span>><li> <a href="{{ forum.get_absolute_url }}">{{ forum.name }}</a></li>{% endifnotequal %}{% endif %}
{% if title %} <span class="divider">/</span><li class="active">{{ title }}</li>{% endif %}
{% endblock %}

{% block userbar %}
{% if user.is_authenticated %}
  <div class="btn-group">
    <a href="{% url forum_new_posts %}" class="btn">View New Posts</a>
    {% if nodejs %}
    <a href="{% url forum_stalk_users %}" class="btn">Stalk Users</a>
    {% endif %}
    <a href="{% url forum_search %}" class="btn">Search</a>
    {% block userbar_extra %}{% endblock %}
  </div>
{% else %}
  <div "btn-group">
    <a href="{% url account_login %}">Log in</a> or <a href="{% url account_signup %}">Sign up</a>
  </div>
{% endif %}
{% endblock %}



eveauth/apps/forum/templates/forum/delete_forum.html
{% extends "forum/base.html" %}{% load forum_tags %}
{% block main_content %}
<p class="description">Are you sure you want to delete the <strong>{{ forum.name }}</strong> forum?</p>
{% if topic_count %}
<p>This will result in the deletion of its {{ topic_count }} topic{{ topic_count|pluralize }} and all {{ topic_count|pluralize:"its,their" }} posts.</p>
{% endif %}
<form name="deleteSectionForm" id="deleteForumForm" action="{% url forum_delete_forum forum.id %}" method="POST">
{% csrf_token %}
<div class="buttons">
  <input type="submit" value="Confirm Deletion">
  or
  <a href="{{ forum.get_absolute_url }}">Cancel</a>
</form>
{% endblock %}

eveauth/apps/forum/templates/forum/edit_forum.html
{% extends "forum/base.html" %}
{% block main_content %}
<form name="editForumForm" id="editForumForm" action="." method="POST">
{% csrf_token %}
  <fieldset class="module aligned">
    <h2>Forum</h2>
    <div class="form-row">
      {% if form.name.errors %}{{ form.name.errors.as_ul }}{% endif %}
      {{ form.name.label_tag }}
      <div class="form-field">
        {{ form.name }}
      </div>
    </div>
    <div class="form-row">
      {% if form.description.errors %}{{ form.description.errors.as_ul }}{% endif %}
      {{ form.description.label_tag }}
      <div class="form-field">
        {{ form.description }}
      </div>
    </div>
  </fieldset>
  <div class="buttons">
    <input type="submit" name="submit" value="Edit Forum">
    or
    <a href="{{ forum.get_absolute_url }}">Cancel</a>
  </div>
</form>
{% endblock %}

eveauth/apps/forum/templates/forum/forum_index.html
{% extends "forum/base.html" %}{% load forum_tags %}
{% block main_content %}
{% if user|is_admin %}
<div class="row btn-group">
    <a href="{% url forum_add_section %}" class="btn btn-primary">Add Section</a>
</div>
<div class="row">
    <br/>
</div>
{% endif %}
{% for section,forum_list in section_list %}
<div class="row">
<table class="table table-striped table-bordered">
    <col width="60%">
    <col width="10%">
    <col width="40%">
<thead>
    <tr><td colspan="3"><h2><a href="{{ section.get_absolute_url }}">{{ section.name }}</a></h2></tr>
  <tr>
    <th>Forum</th>
    <th>Topics</th>
    <th>Last Post</th>
  </tr>
</thead>
<tbody>

{% if forum_list %}
{% for forum in forum_list %}
  <tr class="forum {% cycle odd,even %}">
    <td>
      <a href="{{ forum.get_absolute_url }}">{{ forum.name }}</a>
      {% if forum.description %}<p class="description">{{ forum.description }}</p>{% endif %}
    </td>
    <td>{{ forum.topic_count }}</td>
    <td class="last-post">{% if forum.last_post_at %}
      <a href="{% url forum_redirect_to_last_post forum.last_topic_id %}">Last post</a> {{ forum.last_post_at|post_time:user }}<br>
      <strong>In:</strong> <a href="{% url forum_topic_detail forum.last_topic_id %}">{{ forum.last_topic_title }}</a><br>
      <strong>By:</strong> <a href="{% url forum_user_profile forum.last_user_id %}">{{ forum.last_username }}</a>
    {% else %}N/A{% endif %}</td>
  </tr>{% endfor %}
</tbody>
</table>
{% else %}
<div class="module-body">
This Section does not have any Forums yet.
</div>
{% endif %}
</div>
{% endfor %}

{% if redis and active_users %}
<div class="module module-body" id="stats">
<div id="active-users">
<h3>{{ active_users|length }} active user{{ active_users|length|pluralize }} <span class="since">(in the last 30 minutes)</span></h3>
<p>{% for active_user, last_seen in active_users %}
<a href="{% url forum_user_profile active_user.id  %}" title="{{ last_seen|time:"g:i A"}}">{{ active_user.username }}</a>{% if not forloop.last %}, {% endif %}
{% endfor %}</p>
</div>
</div>
{% endif %}
{% endblock %}

eveauth/apps/forum/templates/forum/user_profile.html
{% extends "forum/base.html" %}{% load forum_tags %}
{% block main_content %}
{% ifequal user.id forum_user.id %}
<div class="tools">
  <div class="actions">
    <a href="{% url account_password %}">Change Password</a>
  </div>
</div>
{% endifequal %}
<div class="col-l">
  <div class="module forum-profile">
  <h2><span class="title">{{ title }}</span>{% if user|can_edit_user_profile:forum_user %}<span class="separator"> - </span><span class="controls"><a href="{% url forum_edit_user_forum_profile forum_user.id %}">Edit</a></span>{% endif %}</h2>
  <table>
  <tbody>
    <tr>
      <th>Avatar</th>
      <td>{% if forum_profile.avatar %}<img src="{{ forum_profile.avatar }}" alt=""{{ avatar_dimensions }}>{% else %}None{% endif %}</td>
    </tr>
    <tr>
      <th>Group</th>
      <td>{{ forum_profile.get_group_display }}</td>
    </tr>
    <tr>
      <th>Title</th>
      <td>{{ forum_profile.title|default:"None" }}</td>
    </tr>
    <tr>
      <th>Posts</th>
      <td>{{ forum_profile.post_count }}</td>
    </tr>
    <tr>
      <th>Joined</th>
      <td>{{ forum_user.date_joined|joined_date }}</td>
    </tr>
    <tr>
      <th>Location</th>
      <td>{% if forum_profile.location %}{{ forum_profile.location }}{% else %}None{% endif %}</td>
    </tr>
    <tr>
      <th>Website</th>
      <td>{% if forum_profile.website %}<a href="{{ forum_profile.website }}">{{ forum_profile.website }}</a>{% else %}None{% endif %}</td>
    </tr>
    {% if redis %}
    <tr>
      <th>Last Seen</th>
      <td>{{ last_seen|timesince }}</td>
    </tr>
    <tr>
      <th>Doing</th>
      <td>{{ doing|safe }}</td>
    </tr>
    {% endif %}
  </tbody>
  </table>
  </div>

  {% ifequal user.id forum_user.id %}
  <div class="module forum-settings">
  <h2><span class="title">Your Forum Settings</span><span class="separator"> - </span><span class="controls"><a href="{% url forum_edit_user_forum_settings %}">Edit</a></span></h2>
  <table>
  <tbody>
    <tr>
      <th>Timezone</th>
      <td>{{ forum_profile.timezone|default:"None" }}</td>
    </tr>
    <tr>
      <th>Topics Per Page</th>
      <td>{{ forum_profile.topics_per_page|default:"Default" }}</td>
    </tr>
    <tr>
      <th>Posts Per Page</th>
      <td>{{ forum_profile.posts_per_page|default:"Default" }}</td>
    </tr>
    <tr>
      <th>Auto Fast Reply</th>
      <td>{{ forum_profile.auto_fast_reply|yesno:"Yes,No" }}</td>
    </tr>
  </tbody>
  </table>
  </div>
  {% endifequal %}
</div>

<div class="col-r">
<div class="module last-topics-started">
<h2><span class="title">Most Recent Topics Started</span>{% if recent_topics %}<span class="separator"> - </span><span class="controls"><a href="{% url forum_user_topics forum_user.id %}">View All Topics</a></span>{% endif %}</h2>
{% if recent_topics %}
{% load humanize %}
<table>
<col width="35%">
<col width="15%">
<col>
<col width="1">
{% if redis %}<col width="1">{% endif %}
<col width="20%">
<thead>
  <tr>
    <th>Topic</th>
    <th>In Forum</th>
    <th>Started</th>
    <th>Posts</th>
    {% if redis %}<th>Views</th>{% endif %}
    <th>Last Post</th>
  </tr>
</thead>
<tbody>
{% for topic in recent_topics %}
  <tr class="topic {% cycle odd,even %}{% if topic.hidden %} hidden-topic{% endif %}">
    <td>
      {% if topic.hidden %}<img src="{{ STATIC_URL }}forum/img/icon_exclamation.gif" alt="Hidden" title="This topic is hidden">{% endif %}
      {% if topic.locked %}<img src="{{ STATIC_URL }}forum/img/icon_lock.gif" alt="Locked" title="This topic is locked">{% endif %}
      <a href="{{ topic.get_absolute_url }}">{{ topic.title }}</a>
      {% if topic.description %}<p class="description">{{ topic.description }}</p>{% endif %}
    </td>
    <td><a href="{% url forum_forum_detail topic.forum_id %}">{{ topic.forum_name }}</a></td>
    <td>{{ topic.started_at|timesince }} ago</td>
    <td class="posts"><a href="{% url forum_topic_post_summary topic.id %}" class="topic-post-summary">{{ topic.post_count|intcomma }}</a></td>
    {% if redis %}<td class="views">{{ topic.view_count|intcomma }}</td>{% endif %}
    <td class="last-post">{{ topic.last_post_at|post_time:user }}<br><a href="{% url forum_redirect_to_last_post topic.id %}">Last Post</a> by <a href="{% url forum_user_profile topic.last_user_id %}">{{ topic.last_username }}</a></td>
  </tr>{% endfor %}
</tbody>
</table>
{% else %}
<div class="module-body">
This user has not started any Topics yet.
</div>
{% endif %}
</div>
</div>
{% endblock %}